services:
  - type: web
    name: my-hall
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: DB_CONNECTION
        value: sqlite
      - key: APP_URL
        value: https://my-wedding-projects.onrender.com
      - key: RENDER
        value: "true"

